services:
  wallet-api:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  localstack:
    image: localstack/localstack:latest
    container_name: sns
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=access-key
      - AWS_SECRET_ACCESS_KEY=secret-key
    volumes:
      - ./scripts/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
      - /var/run/docker.sock:/var/run/docker.sock
